services:
  redis:
    image: redis:latest
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  discord:
    image: nmd_downloader
    build:
      context: .
    container_name: discord
    restart: unless-stopped
    command: ["python", "-m", "apps.discord_app"]
    develop:
      watch:
        - action: sync
          path: .
          target: /NMDownloader
          ignore:
            - __pycache__


  celery:
    image: nmd_downloader
    container_name: celery
    restart: unless-stopped
    command: ["celery", "--app", "apps.celery_app", "worker"]
    volumes:
      - ${DOWNLOAD_PATH}:${DOWNLOAD_PATH}
    environment:
      - C_FORCE_ROOT="true"
    healthcheck:
      test: celery --app apps.celery_app status
      interval: 10s
      timeout: 10s
      retries: 10
    develop:
      watch:
        - action: sync
          path: .
          target: /NMDownloader
          ignore:
            - __pycache__

  flower:
    depends_on:
      celery:
        condition: service_healthy
    image: nmd_downloader
    container_name: flower
    restart: unless-stopped
    ports:
      - "5555:5555"
    command: ["celery", "--app", "apps.celery_app", "flower"]
    environment:
      - FLOWER_UNAUTHENTICATED_API=true
      - FLOWER_URL_PREFIX=flower

  flask:
    depends_on:
      celery:
        condition: service_healthy
    image: nmd_downloader
    container_name: flask
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: [
      "gunicorn",
      "--workers", "${CONCURRENCY:-2}",
      "--bind", "0.0.0.0",
      "apps.flask_app:flask_app",
      "--access-logfile", "-",
      "--error-logfile", "-",
      "--log-level", "${LOG_LEVEL:-INFO}"]
    develop:
      watch:
        - action: sync
          path: .
          target: /NMDownloader
          ignore:
            - __pycache__

volumes:
  redis-data:
